services:
  coupon-bot:
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - ./:/app
      - ${DATA_DIR:-./data}:/data
      - ${CONFIG_DIR:-./config}:/config:ro
      - ${RUNTIME_DIR:-./runtime}:/app/runtime

  coupon-ui:
    ports:
      - "${UI_HOST_PORT:-8080}:8080"
    volumes:
      - ./:/app
      - ${DATA_DIR:-./data}:/data
      - ${CONFIG_DIR:-./config}:/config:ro
      - ${RUNTIME_DIR:-./runtime}:/app/runtime
